name: file_upload_app_part2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  flutter_form_builder: ^9.3.0
  form_builder_validators: ^11.0.0
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.2.1+1
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  path: ^1.9.0
  open_file: ^3.3.2
  image: ^4.2.0
  pdf: ^3.11.0
  permission_handler: ^11.3.1
  file_picker: ^8.0.6
  device_info_plus: ^10.1.0
  flutter_pdfview: ^1.3.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  google_ml_kit: ^0.18.0
  google_mlkit_text_recognition: ^0.13.0
  http_parser: ^4.0.2
  flutter_image_compress: ^2.3.0
  image_picker: ^1.1.2
  syncfusion_flutter_pdfviewer: ^26.2.7
  pdf_render: ^1.4.10
  edge_detection: ^1.1.3
  image_cropper: ^8.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ">=2.3.0 <4.0.0"
  retrofit_generator: ^8.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/google_credentials/extracttextfromimage-429908-be63aaee455a.json
    - assets/OpenSans-VariableFont_wdth,wght.ttf
    - assets/TempProfileImage.png
    - assets/TempProfileImage1.png