name: file_upload_app_part2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  retrofit:
  dio:
  json_annotation:
  json_serializable:
  path_provider: ^2.1.4
  open_file:
  image:
  pdf:
  flutter_pdfview: ^1.3.2
  bloc: ^8.1.4
  http_parser:
  image_picker:
  intl:
  google_ml_kit:
  fluttertoast:
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  permission_handler: ^11.3.1
  equatable: ^2.0.5
  flutter_login: ^5.0.0
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ">=2.3.0 <4.0.0"
  retrofit_generator: ^8.1.1
  dependency_validator: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_credentials/extracttextfromimage-429908-be63aaee455a.json
    - assets/OpenSans-VariableFont_wdth,wght.ttf
    - assets/TempProfileImage.png
    - assets/TempProfileImage1.png
    - assets/pdf_icon.png
    - assets/ocr_icon.png
    - assets/scan_icon.png
    - assets/gallery_icon.png
    - assets/camera_icon.png
    - assets/modify_icon.png