name: file_upload_app_part2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  flutter_form_builder:
  form_builder_validators:
  retrofit:
  dio:
  json_annotation:
  json_serializable:
  camera:
  path_provider:
  path:
  open_file:
  image:
  pdf:
  permission_handler:
  file_picker:
  device_info_plus:
  flutter_pdfview:
  bloc:
  flutter_bloc:
  http_parser:
  flutter_image_compress:
  image_picker:
  syncfusion_flutter_pdfviewer:
  pdf_render:
  edge_detection:
  image_cropper:
  intl:
  google_ml_kit:
  google_mlkit_text_recognition:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ">=2.3.0 <4.0.0"
  retrofit_generator: ^8.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/google_credentials/extracttextfromimage-429908-be63aaee455a.json
    - assets/OpenSans-VariableFont_wdth,wght.ttf
    - assets/TempProfileImage.png
    - assets/TempProfileImage1.png